CREATE TABLE `VehicleInfo` (
    `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `vin` VARCHAR(17) NOT NULL,
    `vendor` VARCHAR(255) NOT NULL, -- VAG
    `make` VARCHAR(255) NOT NULL, -- Audi
    `name` VARCHAR(255) NOT NULL, -- Audi Q2 Sport
    `year` YEAR(4) NOT NULL, -- 2018

    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    UNIQUE KEY `vin` (`vin`)
)
ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
COMMENT 'Basic vehicle information'
;

EXIT -- ROLLBACK

DROP TABLE `VehicleInfo`;
